name: Bug report
description: File a bug report
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of the problem.
      placeholder: Describe the bug
    validations:
      required: true
