name: Feature request
description: Suggest an idea
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
      description: Describe the feature and why it's useful.
    validations:
      required: true
