name: CI
on:
  push: { branches: [ "main" ] }
  pull_request: { branches: [ "main" ] }
jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: Install-Module PSScriptAnalyzer -Scope CurrentUser -Force
      - name: Lint src (fail only on errors)
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path src -Recurse -Severity Information,Warning,Error
          $results | Format-Table
          if (($results | Where-Object Severity -eq 'Error')) { exit 1 } else { exit 0 }
