name: Release Pack

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create zip
        run: |
          zip -r m365-compliance-setup.zip . -x '*.git*' 'Reports/*'
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: m365-compliance-setup
          path: m365-compliance-setup.zip
